---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: radio
data:
  mosquitto.conf: |
    per_listener_settings false

    log_dest stdout
    log_type all

    allow_anonymous false
    password_file /mosquitto/config/passwd

    persistence false

    listener 1883
    protocol mqtt

  passwd: |
    {{ secrets.mosquitto_passwd | indent }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: radio
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0
          volumeMounts:
            - mountPath: "/mosquitto/config"
              name: mosquitto-config

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: radio
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      nodePort: 31883
