---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-actor-config
  namespace: radio
data:
  debug.txt: |
    0  | dapnet/m0nxn | M0NXN: is this thing on?
    30 | dapnet/m0nxn | M0NXN: is this thing still on?
    60 | dapnet/m0nxn | M0NXN: is this thing still on now?

  m0nxn.txt: |
    Fri, 03 Jun 2022 07:00:00 +0100 | dapnet/m0nxn | M0NXN: Get out of bed
    Sat, 04 Jun 2022 07:00:00 +0100 | dapnet/m0nxn | M0NXN: Get out of bed
    Sun, 05 Jun 2022 07:00:00 +0100 | dapnet/m0nxn | M0NXN: Get out of bed
    Mon, 06 Jun 2022 07:00:00 +0100 | dapnet/m0nxn | M0NXN: Get out of bed

  countdown.txt: |
    Mon, 30 May 2022 10:15:00 +0100 | dapnet/emfcamp/announcements | EMF is getting close!
    Mon, 30 May 2022 11:00:00 +0100 | dapnet/emfcamp/announcements | EMF is getting closer!
    Tue, 31 May 2022 10:00:00 +0100 | dapnet/emfcamp/announcements | Such EMF, very soon. wow.
    Wed, 01 Jun 2022 10:00:00 +0100 | dapnet/emfcamp/announcements | Another generic message about EMF being soon
    Thu, 02 Jun 2022 10:00:00 +0100 | dapnet/emfcamp/announcements | Are you on your way to EMF yet?

  schedule_dapnet.txt: |
    {{ lookup('file', 'schedule/dapnet.txt') | indent(4) }}

  schedule_printer.txt: |
    {{ lookup('file', 'schedule/printer.txt') | indent(4) }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-actor
  namespace: radio
  labels:
    app: mqtt-actor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-actor
  template:
    metadata:
      labels:
        app: mqtt-actor
    spec:
      volumes:
        - name: mqtt-actor-config
          configMap:
            name: mqtt-actor-config
      containers:
        - name: mqtt-actor
          image: ghcr.io/dannixon/mqtt-actor:v1.4.0
          env:
            - name: RUST_LOG
              value: debug
            - name: MQTT_BROKER
              value: tcp://mqtt.mqtt.svc.cluster.local:1883
            - name: MQTT_USERNAME
              value: mqtt_actor
            - name: MQTT_PASSWORD
              value: "{{ secrets.mqtt_passwords.mqtt_actor }}"
          volumeMounts:
            - mountPath: /config
              name: mqtt-actor-config
