---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-actor-config
  namespace: radio
data:
  debug.txt: |
    0 | emfcamp/announcements | M0NXN: this is a test, ignore plz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-actor
  namespace: radio
  labels:
    app: mqtt-actor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-actor
  template:
    metadata:
      labels:
        app: mqtt-actor
    spec:
      volumes:
        - name: mqtt-actor-config
          configMap:
            name: mqtt-actor-config
      containers:
        - name: mqtt-actor
          image: ghcr.io/dannixon/mqtt-actor:v1.2.0
          env:
            - name: RUST_LOG
              value: debug
            - name: MQTT_BROKER
              value: tcp://mqtt.radio.svc.cluster.local:1883
            - name: MQTT_USERNAME
              value: mqtt_actor
            - name: MQTT_PASSWORD
              value: "{{ secrets.mqtt_passwords.mqtt_actor }}"
          volumeMounts:
            - mountPath: /config
              name: mqtt-actor-config
