---
apiVersion: v1
kind: Secret
metadata:
  name: printer-controller-secrets
  namespace: printer
data:
  MQTT_PASSWORD: "{{ secrets.mqtt_passwords.printer_publisher | b64encode }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: printer-controller
  namespace: printer
  labels:
    app: printer-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: printer-controller
  template:
    metadata:
      labels:
        app: printer-controller
    spec:
      containers:
        - name: printer-controller
          image: ghcr.io/dannixon/emfcamp-2022-printer-controller:b100a392d5f6c68c2b5fb95813ad6fd50db8fa9a
          envFrom:
            - secretRef:
                name: printer-controller-secrets
