---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install ansible ansible-lint

      - name: Ansible Lint
        run: ansible-lint

  config-generator-formatting-and-quality:
    name: config-generator Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup
        run: rustup component add clippy rustfmt

      - name: Format
        run: cd config-generator && cargo fmt -- --check

      - name: Clippy
        run: cd config-generator && cargo clippy -- -Dwarnings

  config-generator-build-and-test:
    name: config-generator Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and Test
        run: cd config-generator && cargo test
