---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install ansible ansible-lint

      - name: Ansible Lint
        run: ansible-lint
