---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-latest

    steps:
      - uses: dannixon/ansible-testing/actions/lint@main

  config-generator-formatting-and-quality:
    name: config-generator Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: rustup component add clippy rustfmt

      - name: Format
        run: cd config-generator && cargo fmt -- --check

      - name: Clippy
        run: cd config-generator && cargo clippy -- -Dwarnings

  config-generator-build-and-test:
    name: config-generator Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        run: cd config-generator && cargo test

  printer-controller-container-image:
    name: printer-controller container image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Derive tags
        run: |
          echo 'tags<<EOF' >> $GITHUB_ENV
          echo "${{ github.ref_name }} ${{ github.sha }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: emfcamp-2022-printer-controller
          tags: "${{ env.tags }}"
          context: ./printer-controller
          containerfiles: ./printer-controller/Containerfile
          oci: true

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/dannixon
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
